# Generated by Django 4.2.6 on 2023-11-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("INPROGRESS", "Inprogress"),
                    ("DELIVERED", "Delivered"),
                    ("INACTIVE", "Inactive"),
                ],
                default="INPROGRESS",
            ),
        ),
    ]
