# Generated by Django 4.2.6 on 2024-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletters", "0002_alter_newsletter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("INPROGRESS", "Inprogress"),
                    ("DELIVERED", "Delivered"),
                    ("INACTIVE", "Inactive"),
                ],
                default="UPCOMING",
            ),
        ),
    ]
