# Generated by Django 4.2.6 on 2023-10-20 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("BIWEEKLY", "Biweekly"),
                            ("QUARTERLY", "Quarterly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="BIWEEKLY",
                    ),
                ),
                ("logo_url", models.TextField()),
                ("last_issue_date", models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MEMBER", "Member"),
                            ("OWNER", "Owner"),
                        ]
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                through="groups.Members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
