# Generated by Django 4.2.6 on 2023-10-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="last_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="logo_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
