# Generated by Django 4.2.6 on 2023-10-20 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_alter_group_last_issue_date_alter_group_logo_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
    ]
