# Generated by Django 4.2.6 on 2023-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_rename_members_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(choices=[("ADMIN", "Admin"), ("MEMBER", "Member")]),
        ),
    ]
