name: black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install black and run black check
        run: |
          pip install black
          black --check --verbose --extend-exclude migrations .