name: flake8 lint
on: [push, pull_request]
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install flake8 and run flake8 lint
        run: |
          pip install flake8
          python -m flake8 --ignore E203,E501,W503  --exclude migrations --max-line-length 88 .

