name: isort
on: [pull_request]
jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Verify isort
        uses: isort/isort-action@v1
        with:
          requirements-files: "requirements.txt"